version: '3.8'

services:
  # 1. The Database Service
  postgres:
    image: postgres:15-alpine
    container_name: expense_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: DesingericaTuckavac763!@ # Change this!
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # THIS IS CRITICAL

  # 2. Your Spring Boot Backend (For later)
  backend:
    build: .
    container_name: expense_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/expense_tracker
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=DesingericaTuckavac763!@
    depends_on:
      - postgres

# This tells Docker to save the database files permanently on the host machine
volumes:
  pgdata: